# Generated by Django 4.2.3 on 2023-10-15 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name_last_name', models.CharField(max_length=100, verbose_name='نام')),
                ('phone_number', models.CharField(max_length=15, verbose_name='شماره موبایل')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('contact_note', models.CharField(max_length=1000, verbose_name='متن پیام')),
            ],
        ),
    ]
