# Generated by Django 4.2.3 on 2023-10-24 15:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0003_alter_category_datetime_created_alter_category_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='Order Total Price')),
                ('is_paid', models.BooleanField(default=False, verbose_name='وضعیت پرداخت')),
                ('order_status', models.CharField(choices=[('processing', 'Processing'), ('Completed', 'Completed'), ('no_answer', 'No Answer'), ('wrong_info', 'Wrong Information')], default='processing', max_length=10, verbose_name='Order Status')),
                ('first_name', models.CharField(max_length=100, verbose_name='نام ')),
                ('last_name', models.CharField(max_length=100, verbose_name='نام خانوادگی')),
                ('phone_number', models.CharField(max_length=13, verbose_name='شماره موبایل')),
                ('address', models.CharField(max_length=500, verbose_name='آدرس')),
                ('order_note', models.CharField(blank=True, max_length=500, verbose_name='یادداشت سفارش')),
                ('zarinpal_authority', models.CharField(blank=True, max_length=255, verbose_name='Zarinpal Authority')),
                ('zarinpal_ref_id', models.CharField(blank=True, max_length=150, verbose_name='Zarinpal Ref ID')),
                ('zarinpal_text', models.TextField(blank=True, max_length=700, verbose_name='Zarinpal Response Data')),
                ('datetime_created', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('datetime_modified', models.DateTimeField(auto_now=True, verbose_name='تاریخ تغییر')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='تعداد')),
                ('price', models.PositiveIntegerField(verbose_name='قیمت')),
                ('datetime_created', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='products.product', verbose_name='محصول')),
            ],
        ),
    ]
